let sample_sub = {
  data: [{
    "Item": "001-nyt-16-president-1",
    "Complexity": "Intermediate",
    "Construction": "Interface",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Hue+Pattern",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive slideshow+Free interactions",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "002-nyt-16-republican-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive slideshow+Free interactions",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "003-nyt-16-candidates-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Hue+Value",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Interactive slideshow+Free interactions",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "004-nyt-16-sunnyday-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Map",
    "Encodings": "Geo",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "004-nyt-16-sunnyday-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Line+Area",
    "Encodings": "X+Y",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "005-nyt-16-stephencurry-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Diverging",
    "Sequencing-W": "Single",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "006-nyt-16-europe-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "006-nyt-16-europe-2",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "007-nyt-16-school-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot+Bubble",
    "Encodings": "X+Y+Size",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "007-nyt-16-school-2",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot+Bubble+Line",
    "Encodings": "X+Y+Size+Hue+Orientation",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "007-nyt-16-school-3",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot+Bubble+Line",
    "Encodings": "X+Y+Size+Hue+Orientation",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "008-nyt-16-warmer-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Bar+Line+Area",
    "Encodings": "X+Y+Length",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive Slideshow+V-Linear",
    "Type": "Geospatial",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "009-nyt-16-voter-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "Geospatial",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "010-nyt-16-party-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot+Bubble",
    "Encodings": "X+Y+Size",
    "Sequencing-W": "Single",
    "Sequencing-I": "Single",
    "Type": "Text",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "011-nyt-16-trumpinsult-1",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Area+Stacked",
    "Encodings": "X+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal+Text",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "011-nyt-16-trumpinsult-2",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Area+Stacked",
    "Encodings": "X+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal+Text",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "011-nyt-16-trumpinsult-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal+Text",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "012-nyt-16-culturedivide-1",
    "Complexity": "Intermediate",
    "Construction": "Video",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "012-nyt-16-culturedivide-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "V-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "012-nyt-16-culturedivide-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "013-nyt-16-coldmath-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Free interactions",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "013-nyt-16-coldmath-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Free interactions",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "014-nyt-16-manhattan-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Free interactions",
    "Type": "Geospatial",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "015-nyt-16-florida-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "015-nyt-16-florida-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Table",
    "Encodings": "Hue+X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "015-nyt-16-florida-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "015-nyt-16-florida-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "016-nyt-16-epidemic-1",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "016-nyt-16-epidemic-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "016-nyt-16-epidemic-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "016-nyt-16-epidemic-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "016-nyt-16-epidemic-5",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "017-nyt-16-chicago-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "017-nyt-16-chicago-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "017-nyt-16-chicago-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "017-nyt-16-chicago-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "017-nyt-16-chicago-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "018-nyt-16-murder-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Shape-map",
    "Encodings": "Geo+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "018-nyt-16-murder-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-6",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-7",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "018-nyt-16-murder-9",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "019-nyt-16-glassceiling-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "019-nyt-16-glassceiling-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "Y+X+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "020-nyt-16-muslim-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Cartogram",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "021-nyt-16-indiana-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "021-nyt-16-indiana-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "022-nyt-17-harvey-1",
    "Complexity": "Intermediate",
    "Construction": "Video",
    "Chart_types": "Choropleth+Line",
    "Encodings": "Geo+Hue+X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Animation+Overview",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "022-nyt-17-harvey-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "022-nyt-17-harvey-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bubble-map",
    "Encodings": "Geo+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "022-nyt-17-harvey-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bubble-map",
    "Encodings": "Geo+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "022-nyt-17-harvey-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "022-nyt-17-harvey-6",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area",
    "Encodings": "X+Y+Hue+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "022-nyt-17-harvey-7",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Flow-map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial+Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "022-nyt-17-harvey-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth+Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "022-nyt-17-harvey-9",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Flow-map",
    "Encodings": "Geo+Hue+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Free interactions",
    "Type": "Geospatial+Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "023-nyt-17-gunman-1",
    "Complexity": "Simple",
    "Construction": "Video",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Length+Orientation",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Animation",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "023-nyt-17-gunman-2",
    "Complexity": "Simple",
    "Construction": "Video",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Animation",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "024-nyt-17-gundeath-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot2",
    "Encodings": "Size+Density+Shape",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial+Temporal",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "025-nyt-17-heat-1",
    "Complexity": "Intermediate",
    "Construction": "Video",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "025-nyt-17-heat-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "026-nyt-17-fanmap-1",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "026-nyt-17-fanmap-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "027-nyt-17-rogue-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bubble-map",
    "Encodings": "Geo+Size",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Parallax",
    "Type": "Geospatial",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "027-nyt-17-rogue-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bubble",
    "Encodings": "Size+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "027-nyt-17-rogue-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "028-nyt-17-drawit-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Quiz",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "029-nyt-17-college-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Treemap",
    "Encodings": "Size+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "029-nyt-17-college-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "029-nyt-17-college-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "029-nyt-17-college-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Dot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "030-nyt-17-abnormal-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "030-nyt-17-abnormal-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "031-nyt-17-healthcare-1",
    "Complexity": "Complex",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "031-nyt-17-healthcare-2",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "032-nyt-17-premium-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Length+Value",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "033-nyt-17-trumpworth-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bubble",
    "Encodings": "Size+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "034-nyt-17-france-1",
    "Complexity": "Not-a-visualization",
    "Construction": "Static",
    "Chart_types": "None",
    "Encodings": "Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "034-nyt-17-france-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "034-nyt-17-france-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "034-nyt-17-france-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "035-nyt-17-ransomware-1",
    "Complexity": "Intermediate",
    "Construction": "Video",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Opacity",
    "Sequencing-W": "Single",
    "Sequencing-I": "Animation",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "036-nyt-17-lebron-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "036-nyt-17-lebron-2",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "X+Y+Length+Value",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Small multiples",
    "Type": "General",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "037-nyt-17-britain-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Map",
    "Encodings": "X+Y+Hue+Geo",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "037-nyt-17-britain-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Cartogram",
    "Encodings": "Geo+Hue+Orientation",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "037-nyt-17-britain-3",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "037-nyt-17-britain-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "X+Length+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "037b-nyt-17-thrones-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Shape+Value",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Quiz",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "037b-nyt-17-thrones-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot+Heatmap",
    "Encodings": "X+Y+Value+Size",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Small multiples",
    "Type": "General",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "038-nyt-17-irma-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Flow-map+Line",
    "Encodings": "Geo+X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "Geospatial+Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "039-nyt-17-taxchange-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bubble+Bar",
    "Encodings": "Hue+Size+X+Y+Length",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "040-nyt-17-taxbill-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot+Bubble+Line",
    "Encodings": "X+Y+Size+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "040-nyt-17-taxbill-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "041-nyt-17-alabama-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth+Bar",
    "Encodings": "Geo+X+Diverging",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "041-nyt-17-alabama-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Pie",
    "Encodings": "Angle+Diverging",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "041-nyt-17-alabama-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Hue+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "041-nyt-17-alabama-4",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bubble-map",
    "Encodings": "Geo+Size+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "041-nyt-17-alabama-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue+Value+Shape",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "041-nyt-17-alabama-6",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "042-nyt-17-taxbillcalc-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Free interactions",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "043-nyt-17-cabinet-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Shape",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "043-nyt-17-cabinet-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Shape+Hue+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "043-nyt-17-cabinet-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Shape+Hue+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "043-nyt-17-cabinet-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Shape+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "044-nyt-17-hottest-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "044-nyt-17-hottest-2",
    "Complexity": "Intermediate",
    "Construction": "Video",
    "Chart_types": "Polyline",
    "Encodings": "Angle+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "044-nyt-17-hottest-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Polyline",
    "Encodings": "Angle+Y+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "044-nyt-17-hottest-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Heat-map",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "045-nyt-17-billoreilly-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "045-nyt-17-billoreilly-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "046-nyt-17-drugdeath-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "046-nyt-17-drugdeath-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Hue+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal+Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "046-nyt-17-drugdeath-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Hue+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "046-nyt-17-drugdeath-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "047-nyt-17-rescue-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Parallax",
    "Type": "Geospatial+Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "047-nyt-17-rescue-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "048-nyt-17-subway-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "048-nyt-17-subway-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "048-nyt-17-subway-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "049-nyt-17-northkorea-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot-Map",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "049-nyt-17-northkorea-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "050-nyt-17-summer-1",
    "Complexity": "Simple",
    "Construction": "Video",
    "Chart_types": "Area",
    "Encodings": "X+Y+Size+Hue+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "050-nyt-17-summer-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area",
    "Encodings": "X+Y+Size+Hue+Opacity",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "051-nyt-17-subwayrun-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Line",
    "Encodings": "X+Y+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "051-nyt-17-subwayrun-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "051-nyt-17-subwayrun-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Line",
    "Encodings": "X+Y+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "051-nyt-17-subwayrun-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "052-nyt-17-underrepresent-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "052-nyt-17-underrepresent-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Shape+Length+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "052-nyt-17-underrepresent-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Shape+Length+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "052-nyt-17-underrepresent-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "053-nyt-17-taxplan-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot+Line",
    "Encodings": "X+Y+Orientation+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "053-nyt-17-taxplan-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "053-nyt-17-taxplan-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked",
    "Encodings": "X+Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "053-nyt-17-taxplan-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "053-nyt-17-taxplan-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "054-nyt-17-massshooting-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "054-nyt-17-massshooting-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "112-wsj-17-bombing-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bubble",
    "Encodings": "Hue+Proximity",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "113-wsj-17-immigration-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line+Area+Stacked",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Parallax",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "113-wsj-17-immigration-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area+Stacked",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "114-wsj-17-mindgap-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "Y+Length+Size+Hue+Pattern",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "114-wsj-17-mindgap-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Treemap",
    "Encodings": "Y+Length+Size+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "114-wsj-17-mindgap-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Treemap+Line",
    "Encodings": "Y+X+Length+Size+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear+V-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+X+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Length+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+X+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-5",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+X+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-6",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-7",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "115-wsj-17-franceclass-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot2",
    "Encodings": "Hue+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "115-wsj-17-franceclass-9",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot2",
    "Encodings": "Hue+Size+Shape",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "116-wsj-17-xijinping-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area+Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area+Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Stacked+Line",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area+Stacked",
    "Encodings": "X+Y+Hue+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-6",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-7",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "116-wsj-17-xijinping-9",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Value",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "117-wsj-17-techrally-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "118-wsj-17-trumptweet-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "118-wsj-17-trumptweet-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "119-wsj-17-octobersnot-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "119-wsj-17-octobersnot-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "119-wsj-17-octobersnot-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "119-wsj-17-octobersnot-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "120-wsj-17-goptax-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Bar",
    "Encodings": "X",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "121-wsj-17-ceopay-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Parallax",
    "Type": "Gerneral",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "121-wsj-17-ceopay-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Value+Length",
    "Sequencing-W": "Overview",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "121-wsj-17-ceopay-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Length+Shape+Y",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "121-wsj-17-ceopay-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "122-wsj-17-goptaxcal-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Free interactions",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "122-wsj-17-goptaxcal-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot",
    "Encodings": "Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "123-wsj-17-giant-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Polar",
    "Encodings": "Angle+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "123-wsj-17-giant-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Polar",
    "Encodings": "Angle+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "123-wsj-17-giant-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Polar",
    "Encodings": "Angle+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "124-wsj-17-giant20-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "124-wsj-17-giant20-5",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Area+Stacked",
    "Encodings": "X+Y+Hue+Size",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "124-wsj-17-giant20-6",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Area+Stacked",
    "Encodings": "X+Y+Hue+Size",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "124-wsj-17-giant20-7",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "124-wsj-17-giant20-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Diverging",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-9",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Y+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-10",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "124-wsj-17-giant20-11",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "124-wsj-17-giant20-12",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Area",
    "Encodings": "X+Y",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "125-wsj-17-trumpchildren-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Network",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "126-wsj-17-heathcare-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue+Shape",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "126-wsj-17-heathcare-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue+Shape+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "126-wsj-17-heathcare-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue+Shape+Value",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "126-wsj-17-heathcare-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Hue+Shape",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "126-wsj-17-heathcare-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot",
    "Encodings": "X+Y",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "127-wsj-17-thenandnow-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot2",
    "Encodings": "Value+Size+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "127-wsj-17-thenandnow-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Pie",
    "Encodings": "Angle+Hue+Value",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "128-wsj-16-election-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value+Diverging",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive slideshow",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "129-wsj-16-counties-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "129-wsj-16-counties-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth+Line+Heatmap",
    "Encodings": "Geo+Diverging+Hue+X+Y",
    "Sequencing-W": "Overview",
    "Sequencing-I": "H-Linear+V-Linear",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "130-wsj-16-jets-1",
    "Complexity": "Simple",
    "Construction": "Video",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Animation",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "131-wsj-16-times-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "131-wsj-16-times-2",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "132-wsj-16-megabank-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Area+Stacked+Line",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "133-wsj-16-splinter-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Heatmap",
    "Encodings": "Hue+X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Free Interactions",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "133-wsj-16-splinter-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Heatmap",
    "Encodings": "Hue+X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "134-wsj-16-zika-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "134-wsj-16-zika-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "134-wsj-16-zika-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "134-wsj-16-zika-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "134-wsj-16-zika-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Value",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "135-wsj-16-bankstress-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Bar",
    "Encodings": "Y+Length+Shape+Hue+X",
    "Sequencing-W": "Single",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "136-wsj-16-candidates-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Y+Length+Shape+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "137-wsj-16-redblue-1",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Cartogram+Bar",
    "Encodings": "Geo+X+Y+Hue",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "137-wsj-16-redblue-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "Hue+X+Y",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "138-wsj-16-paygap-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Bar",
    "Encodings": "Y+Length+Hue+X",
    "Sequencing-W": "Single",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "139-wsj-16-trumphappen-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bubble",
    "Encodings": "Size+Proximity",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "140-wsj-16-elecmap-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Cartogram+Choropleth",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "Geospatial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "140-wsj-16-elecmap-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "140-wsj-16-elecmap-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "140-wsj-16-elecmap-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "141-wsj-16-swing-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Length+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Free interactions",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "141-wsj-16-swing-2",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Bar+Stacked",
    "Encodings": "Length+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Free interactions",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "142-wsj-16-gendeworkplace-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "Length+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Animation",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "142-wsj-16-gendeworkplace-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Quiz",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "142-wsj-16-gendeworkplace-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "143-wsj-16-whatpercet-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Bar+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Free interactions",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "144-wsj-16-econgravity-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Area",
    "Encodings": "Hue+Size",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Interactive Slideshow",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "145-wsj-16-popularity-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Y+Length+Hue+Value",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "145-wsj-16-popularity-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Y+Length+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "145-wsj-16-popularity-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "145-wsj-16-popularity-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "In-column",
    "Size2": "small"
  },
  {
    "Item": "146-wsj-16-divided-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Scatterplot",
    "Encodings": "X+Y+Diverging",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "General",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "146-wsj-16-divided-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Choropleth",
    "Encodings": "Geo+Diverging",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geosptial",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "146-wsj-16-divided-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar+Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "147-wsj-16-polling-1",
    "Complexity": "Intermediate",
    "Construction": "Dynamic",
    "Chart_types": "Line+Scatterplot",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "147-wsj-16-polling-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "Small multiples",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "147-wsj-16-polling-3",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Overview+V-Linear",
    "Sequencing-I": "H-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "148-wsj-16-boardrooms-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Dot2",
    "Encodings": "Size+Value+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Parallax+Interactive Slideshow",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "149-wsj-16-topceos-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Bubble+Bar",
    "Encodings": "X+Size+Hue+Length",
    "Sequencing-W": "Single",
    "Sequencing-I": "Overview",
    "Type": "General",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "150-wsj-16-startupstock-1",
    "Complexity": "Simple",
    "Construction": "Interface",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue+Shape",
    "Sequencing-W": "Single",
    "Sequencing-I": "Overview",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "151-wsj-16-winningstock-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue+Value",
    "Sequencing-W": "Single",
    "Sequencing-I": "Quiz",
    "Type": "Temporal",
    "Size": "Entire page",
    "Size2": "big"
  },
  {
    "Item": "152-wsj-16-howbond-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "152-wsj-16-howbond-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-4",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-5",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-6",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-7",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "152-wsj-16-howbond-8",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "152-wsj-16-howbond-9",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "153-wsj-16-homerebound-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "153-wsj-16-homerebound-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "153-wsj-16-homerebound-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "153-wsj-16-homerebound-4",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "154-wsj-16-polling-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Length+Shape+Hue+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "154-wsj-16-polling-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Bar",
    "Encodings": "X+Length+Shape+Hue+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "155-wsj-16-rollin-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Overview",
    "Type": "General+Temporal",
    "Size": "Long",
    "Size2": "big"
  },
  {
    "Item": "155-wsj-16-rollin-2",
    "Complexity": "Intermediate",
    "Construction": "Static",
    "Chart_types": "Heatmap",
    "Encodings": "Hue+X+Y",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Overview",
    "Type": "General",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "156-wsj-16-hillary-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area",
    "Encodings": "X+Y+Size+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "156-wsj-16-hillary-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Area",
    "Encodings": "X+Y+Size+Hue",
    "Sequencing-W": "In-text",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "156-wsj-16-hillary-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Boxplot",
    "Encodings": "X+Y+Hue+Length",
    "Sequencing-W": "In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "157-wsj-16-delegate-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Free interactions",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "158-wsj-16-clintonsanders-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line+Area",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "158-wsj-16-clintonsanders-2",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "158-wsj-16-clintonsanders-3",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Bar",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "V-Linear",
    "Sequencing-I": "Single",
    "Type": "Temporal",
    "Size": "Column-wide",
    "Size2": "medium"
  },
  {
    "Item": "159-wsj-16-repulican-1",
    "Complexity": "Simple",
    "Construction": "Static",
    "Chart_types": "Cartogram",
    "Encodings": "Geo+Hue",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "Single",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "159-wsj-16-repulican-2",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Cartogram+Bar",
    "Encodings": "Geo+Hue+Length",
    "Sequencing-W": "Overview+In-text",
    "Sequencing-I": "V-Linear",
    "Type": "Geospatial",
    "Size": "Page-wide",
    "Size2": "big"
  },
  {
    "Item": "160-wsj-16-swinging-1",
    "Complexity": "Simple",
    "Construction": "Dynamic",
    "Chart_types": "Dot+Line",
    "Encodings": "X+Y+Hue",
    "Sequencing-W": "Single",
    "Sequencing-I": "Small multiples",
    "Type": "Geospatial+Temporal",
    "Size": "Long",
    "Size2": "big"
  }
  ]
}
sample_sub.filtered_items = function (akey, n) {
  let d = sample_sub.data;
  let temp = [];
  for (let i = 0; i < n; i++) {
    let key = akey + "-" + (i + 1).toString();
    let t = d.filter(function (el) { return el.Item == key; })[0];
    if (t) {
      t['ord'] = i + 1;
      t['ct'] = t['Chart_types'].split("+");
      t['ec'] = t['Encodings'].split("+");
      t['sq'] = t['Sequencing-I'].split("+");
      t['dt'] = t['Type'].split("+");
      temp.push(t);
    }
  }
  return temp;
}
